### ISSUE TITLE
Generators ToDo

### ISSUE THREAD

**Issue by wuestenarchitekten** [TouchDesigner/Palette#1]
- [x] all vectors for glsl TOP should be renamed from _vecName_ to _uVecName_
- [x] **mesh COMP:** replace the eval1 DAT with a Parameter DAT
- [x] **mesh COMP:** controls and null1 CHOP not needed if channels are directly referenced in operators
- [x] **mesh COMP:** rename operators like _scaleTy_ to _math_scaleTy_, the pattern should be **opType_function**
- [x] **noise COMP:** there are vectors on Vectors2 page that can use binding and not exports (then remove parameter CHOP and null CHOP)
- [x] **superFormula COMP:** parameter and null CHOP can be removed. rename Script SOPs to reflect functionality

**Comment by brvoigt** [comment]
- [x] **Julia COMP**: Make uniform names similar to parameter name 1) rename uIterInc to uIncrement 2) rename uIterBreak to uIterlimit
- [x] **Julia COMP**: Parameter 'Orbital Texture' -> 'Orbital Trap Map'; token 'Traptop' -> 'Trapmap'
- [x] **Mandelbrot COMP**: Make names and tokens match Julia for 'Center' and 'Orbital Trap Map'
- [x] **Mandelbrot COMP**: Make uniform names match Julia for 1) uIterInc 2) uIterBreak as above.
- [x] **All COMPs**: Setup parameters so that when COMP is loaded they are all at default values. If we want to keep it looking the way it is now (for Julia for example), then the parameter defaults need to be changed to the values it is currently loaded with and resaved. Other option it to "Reset Custom Parameters" and resave. The goal is that when you load in a COMP from palette, ALL parameter are at their default value already, so "Reset Custom Parameters" would have no effect.

- [x] **Noise COMP**: Mirror Noise TOP parameter naming 1) Change parameter 'Type' token to 'Type' 2) Change parameter 'Amplitude' token to 'Amp'
- [x] **Noise COMP**: 'Translate' parameter tokens should be T[xyzw] instead of T[1-4]
- [x] **Noise COMP**: 'Scale' parameter tokens should be S[xyzw] instead of S[1-4]
- [x] **Noise COMP**: 'Clamp Values' tokens should be Clampx and Clampy (NOTE: confirm with markus these clamps are in x and y direction)
- [x] **Noise COMP**: 'Radius' tokens should be Radiusx and Radiusy
- [x] **Noise COMP**: Find out why Radius does not effect polkadots and star types separately in x and y, looks like both values do similar thing
- [x] **Noise COMP**: 'Pixelformat' parameter should match Noise TOP, using a label of "Pixel Format' and a token of 'format'
- [x] **SuperFormula COMP**: '3 Dimensions' rename the label to '3D', token can stay the same.
- [x] **SuperFormula COMP**: Break out 'Resolution' into 2 parameters called 'Rows' and 'Columns', just like Sphere SOP or Grid SOP, and match this inside on the Script SOP called script_3D

**Comment by brvoigt** [comment]
For all palette COMPs that got the docsHelper added, reposition it so it is closer to the network of nodes in the same location each time. We want it close so that when you 'home' the network, you get the best view possible of the network, when it is far away the network will be tiny. See atttached examples
![IdealNoiseCOMP](https://user-images.githubusercontent.com/8110813/54188872-fd5d4280-44f3-11e9-8d66-6623ea66f615.png)
![CurrentNoiseCOMP](https://user-images.githubusercontent.com/8110813/54188873-fd5d4280-44f3-11e9-8a98-f184dbdb693a.png)

**Comment by Jonsil94** [comment]
@brvoigt 
- the style in the custom parameter only goes up to xyz there is no w for the Translate and Scale  
- Markus said the Clamp Values and the Radius values are max min so I renamed the labels to 
"Clamp Min / Max" and "Radius Min / Max" 
- In "Stars 2D" the  glsl only uses the min value "Radius1" but in the parexec cant disable the "Radius2" without disabling both of the values

**Comment by brvoigt** [comment]
@Jonsil94 
- the style in the custom parameter only goes up to xyz there is no w for the Translate and Scale
I don't understand, there are 4 elements to these parameters
![Screen Shot 2019-03-14 at 3 28 20 PM](https://user-images.githubusercontent.com/8110813/54335936-e5113300-466d-11e9-8a7e-4d58ee602fe1.png)

- Markus said the Clamp Values and the Radius values are max min so I renamed the labels to
"Clamp Min / Max" and "Radius Min / Max"
Okay, this is a little non-standard. We should either:
a) call the parameter "Clamp" and and rename the tokens to Clampmin and Clampmax (like we do for Resolution parameters, see image
![Screen Shot 2019-03-14 at 3 35 01 PM](https://user-images.githubusercontent.com/8110813/54336363-32da6b00-466f-11e9-841f-d0a38d51bdba.png)

OR
b) Put them on their own parameters with a slider called Clamp Min and Clamp Max similar to this:
![Screen Shot 2019-03-14 at 3 39 25 PM](https://user-images.githubusercontent.com/8110813/54336441-6c12db00-466f-11e9-9106-a4d5bb8bdba3.png)
What ever you and Markus prefer.

- In "Stars 2D" the glsl only uses the min value "Radius1" but in the parexec cant disable the "Radius2" without disabling both of the values
Maybe this is in support of breaking it out into 2 parameters like I mentioned above in b) option.

**Comment by brvoigt** [comment]
I tested the checked-off items in the list, but these two below do not seem complete although they are marked complete? Did you forget to push your updates to git?

- Noise COMP: 'Pixelformat' parameter should match Noise TOP, using a label of "Pixel Format' and a token of 'format'
- SuperFormula COMP: '3 Dimensions' rename the label to '3D', token can stay the same.

**Comment by Jonsil94** [comment]
@brvoigt 
When I switch to the xyz it cuts out the w 
![Translate](https://user-images.githubusercontent.com/30635468/54373226-437ce800-4653-11e9-8759-0c1cb5fdce6a.PNG)

**Comment by Jonsil94** [comment]
@brvoigt 
I put them in separate parameters 
![ClampRadius](https://user-images.githubusercontent.com/30635468/54373987-94d9a700-4654-11e9-87e2-44d3a7258be1.PNG)

**Comment by brvoigt** [comment]
@Jonsil94 Okay, I reviewed the Custom Parameters documentation and try a few other ways to setup but it looks like there are not ways to rename the 4 floats to have uniquely custom names.
https://docs.derivative.ca/Custom_Parameters

So I have made an RFE for a future change, but for now let's break it out like the Noise TOP does, allowing us to have T[xyz] and S[xyz] and t4d and s4d. You can also disable the t4d and s4d when a 4D noise type is not selected.
