### ISSUE TITLE
ImageFilter ToDo

### ISSUE THREAD

**Issue by wuestenarchitekten** [TouchDesigner/Palette#3]
- [x] general: change all components from Container COMP to Base COMP
- [x] general: wetDryMix, naming should be camelCase
- [x] general: _out2_ in wetDryMix should be named _out1_
- [x] general: for all glsl TOPs or glsl MATs change vector names to _uName_ and sampler names to _sSampler_ (for example _width_ becomes _uWidth_) - watch out for correct camelCase
- [x] **changeColor** simplify the all component to use a Layout TOP instead of the Container COMP network
- [x] **changeToColor** simplify the all component to use a Layout TOP instead of the Container COMP network
- [x] **dilate** see if the res TOP is required, delete if unnecessary
- [x] **feedbackEdge** see if level3 and transform4 TOP is required, delete if unnecessary
- [x] **pixelate** change expression in res2 from the opinfo expression to op('in1').width and height
- [x] **rgbaDelay** change the custom parameters to use negative numbers and bind them to the cacheselects directly
- [x] **sharpen** sharpen amount seems to be the same as dryWetMix, is there a better way to adjust the sharpen level? 
- [x] **softenAlpha** can the logic1 in biasCurve be replaced with a Math and a Limit? -> Math CHOP: Integer:Ceiling and Limit CHOP Clamp:0-1
- [x] **softenAlpha** all exports should be coming from a Null CHOP
- [x] **bloom** set Layout Origin for replicator so that iter Base Comps line up under the master
- [x] **bloom** create a set of good defaults for the custom parameters
- [x] **changeColor/changeToColor** remove unnecessary bg Null TOP in base1/[input/mask/colorMask]
- [x] **changeColor/changeToColor** relayout the input, mask and colorMask base COMPs in base1 so that wires to Layout don't cross.
- [x] **changeColor/changeToColor** rename base1 to something meaningfull: textOverlayAll or so
- [x] **changeToColor** there is a chop chain that selects the Softness custom parameter which is now empty -> the chroma1 TOP has exports missing for Hue Soft Low/High
- [x] **feedback/feebackEdge** change Reset Parameter from Pulse to Momentary and inside bind to the custom parameter. After remove the par execute DAT
- [x] **feebackEdge** after removing ops, relayout the operators so it's nice and tidy (no large spaces between operators when not necessary)
- [x] **hsvBlur** still crashing? if not recolor op to default and enable
- [x] **lightTunnel** since lightTunnel is now a base COMP, remove the panel Execute 
- [x] **lightTunnel** dock the pixel and Info DAT to the glsl2 TOP but keep them exposed, also move the glsl2 a bit down for more clarity in the network
- [x] **pixelRelocator** turn off viewer active for null4_export DAT
- [x] **radialBlur** viewer active on null1 CHOP
- [x] **radialBlur** panelExec DAT not necessary as this is now a Base COMP
- [x] **rgbaDelay** remove unnecessary CHOPs
- [x] **softenAlpha** remove unnecessary null TOP and set display flag to out1 instead of over1
- [x] **twirl** panelExec DAT not necessary as this is now a Base COMP

**Comment by brvoigt** [comment]
- [x] **Bloom COMP**: 'Temporal Smooth' parameter label and 'Feedback' token do not match
- [x] **Bloom COMP**: Change 'Pixel Format' token to 'Format' to match general TOPs
- [x] **Bloom COMP**: 'Pre Shrink' label should be 'Pre-Shrink' like the Blur TOP
- [x] **Change Color COMP**: Use tokens for Hue Offset = Hueoffset, Saturation Multiplier = Satmult, and Value Multiplier = Valmult
- [x] **Change To Color COMP**: Rename tokens Tolerancehue -> Huetolerance, Tolerancesat -> Sattolerance, ToleranceVal -> Valtolerance
- [ ] **Convolve COMP**: Find better naming for Line 1, Line 2, Line 3
- [x] **Feedback Edge COMP**: Not Dry/Wet mix parameter?
- [x] **Feedback Edge COMP**: Add Reset Pulse button in addition to the Reset toggle
- [x] **HSV Blur COMP**: Rename all tokens to use Hue, Sat, and Val instead of H, S, and V
- [x] **Light Tunnel COMP**: 'Center' parameter tokens should be Centerx and Centery
- [x] **Pixel Relocator COMP**: 'Midpoint' and 'Weight' tokens should use x and y not 1 and 2.
- [x] **Pixelate COMP**: Change tokens Hsize = Horzsize and Vsize = Vertsize, Squarepixel = Squarepixels
- [x] **Radial Blur COMP**: 'Center' parameter tokens should be Centerx and Centery
- [x] **RGBA Blur COMP**: For tokens use the words Red, Green, Blue and Alpha instead of R, G, B, A
- [x] **RGBA Delay COMP**: auto connects to any TOP called moviefilein1, resave with no input connected
- [x] **RGBA Delay COMP**: For tokens use the words Red, Green, Blue instead of R, G, B
- [x] **RGBA Delay COMP**: How does 'Alpha Delay' come on, doesn't seem to work.
- [x] **Solarize COMP**: For tokens use Light and Dark instead of L and D
- [x] **Twirl COMP**: 'Center' parameter tokens should be Centerx and Centery

**Comment by Jonsil94** [comment]
@wuestenarchitekten for the sharpen COMP I tried using a par execute to adjust the convolve TOP table
I had to turn on the Normalize Coefficients par on in the convolve top, I uploaded it as "sharpenTest.tox" on github,

 I am not sure if that is correct or if the convolve TOPs works that way?

**Comment by wuestenarchitekten** [comment]
@Jonsil94 just to document it here since we already talked about it: best to use a Evaluate DAT that references the parameter instead of using a CHOPExecute DAT here.
