### ISSUE TITLE
Techniques ToDo

### ISSUE THREAD

**Issue by wuestenarchitekten** [TouchDesigner/Palette#4]
- [x] **KinectPointCloud** add 2 in TOPs and have the Kinect TOPs as default inputs to them
- [x] **KinectPointCloud** add Custom Parameters to choose Kinect Type and Sensor on the Kinect TOPs inside.
- [x] **leapPaint** can we get it to work for both APIs? Version 3 and Version 4? It would need a custom parameter on the outside to choose * swipe_clear missing in ver4 API --> Pulse button 
- [x] **puzzle** can you convert the functions in this to be collapsed into an Extensions? (also check the Timer CHOP (delaying calls))
- [x] **xyScope** add a rename CHOP to make sure all incoming channels are always renamed to tx/ty and change the channelscope for the CHOPto SOP

**Comment by brvoigt** [comment]
list moved to ImageFilters...

**Comment by Jonsil94** [comment]
@brvoigt 
The Reset Pulse button is a "Momentary" button should it still be replaced with a Reset toggle?

**Comment by brvoigt** [comment]
Oh sorry, It looked like a toggle to me, I have never seen the momentary style and it is not standard. Replace it with a Pulse button, it will end up looking like the button on the Feedback TOP that does the resetting

**Comment by brvoigt** [comment]
@wuestenarchitekten @Jonsil94  Sorry, I do not know how this 2nd list of mine ended up here in techniques instead of imagefilters. Also, I am not happy that second lists in the comments here do not show up on the summary page a level higher, you can not see how many are left to do. Oh well, I didn't want to make a full second set of issues for the folder of components though, so thought this was better, next time will get in the correct folder. I moved it just for future reference.

**Comment by brvoigt** [comment]
@wuestenarchitekten Just wondering about the KinectPointCloud addition of Kinect TOPs as default inputs into the In TOPs. I understand the motivation, but won't having Kinect TOPs hidden inside the component then create all sorts of problems for people adding Kinect TOPs outside this component, as it will complain that the Kinect device is 'already in use'. Perhaps just a locked image would be better so other Kinect TOPs will work in the user's project when they are using this component?

**Comment by wuestenarchitekten** [comment]
@brvoigt Yeah - I can see this being a problem. How about we save out a pointcloud and a colorimage from the kinect into the Samples/Map folder and load those in? Then they are generally available for everyone and the kinectPointcloud could be renamed to poincloud?

**Comment by Jonsil94** [comment]
@brvoigt  @wuestenarchitekten  Hey I just updated the puzzle and made the functions into an extension, 

I merged the "randomize" text DAT into the "puzzleExtensions" extension and named the function "randomize2". 
- Could you suggest a better name? or should the function be merged with existing "randomize" function in the "puzzleExtensions"?

had some trouble with the delay, I used the timer chop call back to run the "randomize2" function in the extension with a pulse - "op('timer1').par.start.pulse()" with the delay set to 0.5
- Is there a better way to do this?
- I also tried importing the "time" python module and using time.sleep() but it completely stops touchdesigner for 5 seconds then runs the function.

**Comment by brvoigt** [comment]
@Jonsil94 
- [x] **GestureCapture** - Rename word "Xlate" to "Translate" in the labels, no change to tokens.
- [x] **Kinect PointCloud** - Change Label from "Pointsize" to "PointSize"
- [x] **Kinect PointCloud** - Render Resolution and its accompanying tokens can just be simply "Resolution" and Resolutionw and Resolutionh
- [x] **Kinect PointCloud** - Point Cloud is 2 words, so rename this component kinectPointCloud and the first parameter page should be "Kinect Point Cloud"
- [x] **Motion Sense** - Remove "Camera" from the label of the first 3 parameters

**Comment by brvoigt** [comment]
@Jonsil94 Can you explain what the randomize2 is 'supposed' to do?
Does Randomize2 actually do the move or just count down? It is kind of weird to do the count down each increment with a Timer CHOP, but it does work and yeah you can't sleep python in TD like that.
Markus do you have an idea for inserting the delay?
Maybe a better name for it would be randomizeTimer() or randomizeTimerDelay()

**Comment by Jonsil94** [comment]
I think the randomize2 does the delay and runs the randomize function in the extension. Previously randomize2 was its own DAT and the delay was done with randomize.run( delay in milliseconds) I think  randomizeTimerDelay() would be good? or if there is another way to do the delay
