### ISSUE TITLE
Tools ToDo

### ISSUE THREAD

**Issue by wuestenarchitekten** [TouchDesigner/Palette#5]
- [x] **autoMediaPlayer** there are moviereferences in the moviefilein TOPs that point to a desktop, switch to a expression instead and remove the constant par values
- [x] **equalizer** remove unnecessary CHOPs
- [x] #12
- [x] #11
- [x] **Corner Pin SOP** automatically connects to a Rectange SOP called rectange1. Disconnect and resave the cornerPinSOP comp so it doesn't auto-connect :BV
- [x] **Kinect Calibration** relabel "Projector Resolution" to "Monitor Resolution" :BV
- [x] **Kinect Calibration** rename tokens Gridresolution1 and 2 to Gridresw and Gridresh :BV
- [x] #10
- [x] **Particles GPU** Separate the Particle Size Min Max into 2 parameters and make their tokens Particlesizemin and Particlesizemax :BV 
- [x] **Particles GPU** Turbulence Speed has tokens Turbtrans[1-3]. Make these match the parameter name and x, y, z :BV 
- [x] **Particles GPU** When you set Texture = Custom, it enables the Particle Texture parameter.  There is a number "720" in there, remove this error. Relabel to Particle Texture Map ad rename token to Particlemap :BV 
- [x] **Particles GPU** Separate Fade In and Out Time into 2 separate parameters so the tokens can be descriptive :BV 
- [x] **Projector Blend** Rename tokens Projectresolution1 and 2 to be Projectresolutionx and y :BV
- [ ] #9
- [x] **Projector Blend** Gamma, Hue Adjust RGB, Saturation Adjust RGB and Value Adjust RGB should be RGB type parameters so they have the correct tokens (double check with Markus re Gamma) :BV
- [x] **SOP Render** Contast Color tokens should be Constant[rgb] not Const[rgb] :BV
- [x] **SOP Render** Resolution tokens should be Resolutionw and h :BV

**Comment by Jonsil94** [comment]
@wuestenarchitekten the constant file parameter is being set by the preloader DAT and its grabbing that from the folder1 DAT from the MediaFolder in the parent - (app.samplesFolder) 

So I tried making the inside moviefile TOPs file par to "app.samplesFolder  + '/Map/Nature/Movie.1.mp4'" so that it does not break when it is dragged in but its later replaced with the preloader DAT, does this work?

**Comment by brvoigt** [comment]
@wuestenarchitekten @Jonsil94  
For camSchnappr, some of these are really deep into camSchnapper, so Markus will update he said
- [x] change tokens Opencs and Closecs to Openmain / Closemain, relabel 'Open/Close camSchnappr' to 'Open/Close Main Window' - OR - do we have a better name for this window like Open Calibration Window ( I know they both calibrate) or Open Setup Window
- [x] relabel Hide Guides to Show Guides and invert the default to be on (so no change in functionality, but this is consistent with 'Show Wireframe' below. 
- [x] rename token Random to Colorrandom
- [x] relabel Backlight to Backlight Dimmer, change the token to Blightdimmer, and move it down to below the Backlight Color parameter so it is similar to a Light COMP's parameter layout.
- [x] rename token Aspect to Fix Aspect
- [x] rename token Tangent to Zerotangentdist
- [x] rename token Principal to Fixprincipal

**Comment by wuestenarchitekten** [comment]
@brvoigt Re:sopRender - the Perspective/Ortho is a blend between the two so it should remain a float.

**Comment by Jonsil94** [comment]
@brvoigt @wuestenarchitekten  There is an error in the chromakey comp not sure where it is coming from?
![Error_In_chromakey](https://user-images.githubusercontent.com/30635468/55183405-1a397d00-5166-11e9-9b42-a3b80ce1614f.PNG)

**Comment by wuestenarchitekten** [comment]
there is a DAT Export that is going to the Border Parameters on the Look page. The DAT inside movieplayer is exporting tscript and that can't be evaluated.
Maybe ask Greg if you should replace the MoviePlayer inside chromaKey with his new version or alternatively we should build a very simple movieplayer anyways...

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
